version: '3.9'

services:
  node_backend:
    container_name: node_backend
    image: wordle
    build:
      context: .
    ports:
      - '8080:3000'
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=user
      - PGPASSWORD=test
      - PGDATABASE=defaultdb
      - PGHOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=defaultdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}