version: '3.9'

services:
  node_backend:
    container_name: node_backend
    image: wordle
    build:
      context: .
    ports:
      - '8080:3000'
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=wordle
      - PGHOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wordle}
      PGDATA: /data/mydatabase
    volumes:
      - pgstore:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  pgstore: {}